### ISSUE TITLE
Please update the NPM package

### ISSUE THREAD

**Issue by victorgama** [dazoe/ed25519#3]
I noticed your repository is updated to work with node 0.12+, but the NPM package is outdated. Could you please update the package?

**Comment by KenanSulayman** [comment]
Actually, he can't. Because some developer / company called @stellar [stellar on npm](https://www.npmjs.com/~stellar) cloned the repository and published the module under their name.

*To me, this is a non-acceptable behavior and should be punishable by npm's TOS.*

I wrote the patch for Node 0.12 / iojs; that is, I just published a version that is on-par with master.

`npm install ed25519-native`

Cheers!

**Comment by victorgama** [comment]
Oh dear! Did someone contact NPM support regarding this issue?

Thank you for the information, I will be updating my `package.json` asap.
